// Demo data for Lucknow city issues
// Coordinates are for various locations in Lucknow, India - spaced out to avoid clustering

export interface DemoIssue {
  category: 'garbage' | 'traffic' | 'potholes' | 'water' | 'electricity' | 'streetlights';
  title: string;
  description: string;
  latitude: number;
  longitude: number;
  status: 'pending' | 'in_progress' | 'resolved';
  priority: 'low' | 'medium' | 'high';
  reported_by?: string;
  assigned_to?: string;
}

export const demoIssues: DemoIssue[] = [
  {
    category: 'garbage',
    title: 'Garbage Dumping Near Hazratganj',
    description: 'Large pile of garbage accumulating near Hazratganj market. Needs immediate attention.',
    latitude: 26.8500,
    longitude: 80.9500,
    status: 'pending',
    priority: 'high',
    reported_by: 'Citizen Reporter',
  },
  {
    category: 'traffic',
    title: 'Traffic Light Not Working at Gomti Nagar',
    description: 'Traffic signal at Gomti Nagar intersection is not functioning. Causing traffic congestion.',
    latitude: 26.8800,
    longitude: 81.0000,
    status: 'in_progress',
    priority: 'high',
    reported_by: 'Traffic Department',
    assigned_to: 'Traffic Maintenance Team',
  },
  {
    category: 'potholes',
    title: 'Large Pothole on Kanpur Road',
    description: 'Deep pothole on Kanpur Road near Alambagh. Dangerous for vehicles.',
    latitude: 26.8000,
    longitude: 80.9000,
    status: 'pending',
    priority: 'medium',
    reported_by: 'Local Driver',
  },
  {
    category: 'water',
    title: 'Water Leakage in Indira Nagar',
    description: 'Water pipeline leakage reported in Indira Nagar area. Water wastage observed.',
    latitude: 26.9000,
    longitude: 80.9800,
    status: 'pending',
    priority: 'high',
    reported_by: 'Resident',
  },
  {
    category: 'electricity',
    title: 'Power Outage in Old City',
    description: 'Frequent power cuts in Old City area. Affecting daily life.',
    latitude: 26.8200,
    longitude: 80.9200,
    status: 'in_progress',
    priority: 'high',
    reported_by: 'Local Resident',
    assigned_to: 'Power Department',
  },
  {
    category: 'streetlights',
    title: 'Non-Functional Street Lights on University Road',
    description: 'Multiple street lights not working on University Road. Safety concern at night.',
    latitude: 26.8600,
    longitude: 80.9400,
    status: 'pending',
    priority: 'medium',
    reported_by: 'Student',
  },
  {
    category: 'garbage',
    title: 'Garbage Collection Point Overflowing',
    description: 'Garbage collection point near Ambedkar Park is overflowing. Needs immediate cleanup.',
    latitude: 26.8550,
    longitude: 80.9600,
    status: 'pending',
    priority: 'medium',
    reported_by: 'Local Resident',
  },
  {
    category: 'traffic',
    title: 'Traffic Jam at Charbagh',
    description: 'Heavy traffic congestion at Charbagh railway station area during peak hours.',
    latitude: 26.8300,
    longitude: 80.9100,
    status: 'pending',
    priority: 'low',
    reported_by: 'Commuters',
  },
  {
    category: 'potholes',
    title: 'Multiple Potholes on Sitapur Road',
    description: 'Several potholes on Sitapur Road causing vehicle damage.',
    latitude: 26.8400,
    longitude: 80.8700,
    status: 'resolved',
    priority: 'medium',
    reported_by: 'Road Inspector',
    assigned_to: 'PWD Department',
  },
  {
    category: 'water',
    title: 'Low Water Pressure in Mahanagar',
    description: 'Residents reporting low water pressure in Mahanagar area.',
    latitude: 26.8900,
    longitude: 80.9900,
    status: 'pending',
    priority: 'medium',
    reported_by: 'Resident Association',
  },
  {
    category: 'electricity',
    title: 'Faulty Electric Pole in Aliganj',
    description: 'Electric pole showing sparks in Aliganj. Safety hazard.',
    latitude: 26.8500,
    longitude: 80.9300,
    status: 'pending',
    priority: 'high',
    reported_by: 'Local Shopkeeper',
  },
  {
    category: 'streetlights',
    title: 'Broken Street Light Near Rumi Gate',
    description: 'Street light broken near Rumi Gate. Dark area at night.',
    latitude: 26.8450,
    longitude: 80.9250,
    status: 'pending',
    priority: 'low',
    reported_by: 'Tourist',
  },
  {
    category: 'garbage',
    title: 'Illegal Dumping Site in Trans-Gomti',
    description: 'Illegal garbage dumping site identified in Trans-Gomti area.',
    latitude: 26.9200,
    longitude: 81.0100,
    status: 'pending',
    priority: 'high',
    reported_by: 'Environmental Activist',
  },
  {
    category: 'traffic',
    title: 'Signal Timing Issue at Aminabad',
    description: 'Traffic signal timing needs adjustment at Aminabad intersection.',
    latitude: 26.8350,
    longitude: 80.9150,
    status: 'in_progress',
    priority: 'medium',
    reported_by: 'Traffic Police',
    assigned_to: 'Traffic Control',
  },
  {
    category: 'potholes',
    title: 'Road Damage Near IT College',
    description: 'Severe road damage with multiple potholes near IT College.',
    latitude: 26.8750,
    longitude: 80.9700,
    status: 'pending',
    priority: 'high',
    reported_by: 'College Staff',
  },
];
